CoreShoppingAdminPortal/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreShoppingAdminPortal.Models
{
    public class Brand
    {
        public int BrandId { get; set; }
        public string BrandName { get; set; }

        public string BrandDescription { get; set; }

        public List<Product> Products { get; set; }
    }
}

CoreShoppingAdminPortal/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreShoppingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreShoppingAdminPortal.Controllers
{
    public class BrandController : Controller
    {
        ShopDataDbContext context;
        public BrandController(ShopDataDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            var brands = context.Brands.ToList();

            return View(brands);
        }
        [HttpGet]
        public ViewResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Brand brand)
        {
            context.Brands.Add(brand);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Brand brand = context.Brands.Where(x => x.BrandId == id).SingleOrDefault();

            return View(brand);
        }
        [HttpPost]
        public ActionResult Edit(Brand brand, int id)
        {
            Brand brnd = context.Brands.Where(x => x.BrandId == id).SingleOrDefault();
            context.Entry(brnd).CurrentValues.SetValues(brnd);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            Brand brand = context.Brands.
               Where(x => x.BrandId == id).SingleOrDefault();
            return View(brand);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Brand brnd = context.Brands.Where(x => x.BrandId == id).
                SingleOrDefault();
            return View(brnd);
        }
        [HttpPost]
        public ActionResult Delete(int id, Brand b1)
        {
            Brand brnd = context.Brands.Where(x => x.BrandId == id).
                SingleOrDefault();
            context.Brands.Remove(brnd);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

CoreShoppingAdminPortal/Views/Brand/Create.cshtml
@model CoreShoppingAdminPortal.Models.Brand
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Add Brand</h2>
&nbsp; &nbsp;
<form asp-action="create" asp-controller="Brand">
    <div class="form-group row">
        <label for="text" class="col-sm-2 col-form-label" asp-for="BrandName">Brand Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" placeholder="Text" asp-for="BrandName" />
        </div>
        <br />
        <label for="text" class="col-sm-2 col-form-label" asp-for="BrandDescription">Brand Description</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" placeholder="Text" asp-for="BrandDescription" />
        </div>
        <br />

    </div>
    <center>
        <input type="submit" value="Submit" class="btn btn-success" />&nbsp;
        <button class="btn btn-success" asp-controller="Brand" asp-action="Index">
            Back
        </button>
    </center>
</form>

CoreShoppingAdminPortal/Views/Brand/Delete.cshtml
@model CoreShoppingAdminPortal.Models.Brand
@{ ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h3>Are you sure you want to delete ? </h3>
&nbsp; &nbsp;
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(Model => Model.BrandId)
            </th>
            <th scope="col"> @Html.DisplayNameFor(Model => Model.BrandName)</th>
            <th scope="col"> @Html.DisplayNameFor(Model => Model.BrandDescription)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(Model => Model.BrandId)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.BrandName)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.BrandDescription)
            </td>
        </tr>
    </tbody>
</table>
@using (Html.BeginForm("Delete", "Brand", FormMethod.Post))
{
    <center>
        <input type="submit" value="Delete" class="btn btn-success" />&nbsp;
        <button class="btn btn-success" asp-controller="Brand" asp-action="Index">
            Back
        </button>
    </center>
}

CoreShoppingAdminPortal/Views/Brand/Details.cshtml
@model CoreShoppingAdminPortal.Models.Brand
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Brand Details</h2>
&nbsp;&nbsp;
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(Model => Model.BrandId)
            </th>

            <th scope="col">
                @Html.DisplayNameFor(Model => Model.BrandName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(Model => Model.BrandDescription)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(Model => Model.BrandId)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.BrandName)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.BrandDescription)
            </td>

        </tr>
    </tbody>
</table>
<center>   @Html.ActionLink("Back to List", "Index")</center>

CoreShoppingAdminPortal/Views/Brand/Edit.cshtml
@model CoreShoppingAdminPortal.Models.Brand
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>
<form asp-action="Edit" asp-controller="Brand">
    <div class="form-group row">
        <input type="hidden" asp-for="BrandId" />
        <br />
        <label for="text" class="col-sm-2 col-form-label" asp-for="BrandName">Brand Name</label>
        <div class="col-sm-10">
            <input asp-for="BrandName" />
        </div>
        <label for="text" class="col-sm-2 col-form-label" asp-for="BrandDescription">Brand Description</label>
        <div class="col-sm-10">
            <input asp-for="BrandDescription" />
        </div>
        <br />


    </div>
    <center>
        <input type="submit" value="Edit" class="btn btn-success" />&nbsp;
        <button class="btn btn-success" asp-controller="Brand" asp-action="Index">
            Back
        </button>
    </center>
</form>

CoreShoppingAdminPortal/Views/Brand/Index.cshtml
@model IEnumerable<CoreShoppingAdminPortal.Models.Brand>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<style>

    .btn1 {
        margin-right: 3500px;
        margin-top: -10px;
    }
</style>
<center><h2>Brand Index</h2></center>
    &nbsp;&nbsp;
<a asp-controller="Brand" asp-action="Create"><button type="button" class="btn btn-info btn1">Create</button></a>
    &nbsp;&nbsp;
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.BrandId)</th>
            <th>@Html.DisplayNameFor(model => model.BrandName)</th>
           
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var brand in Model)
        {

            <tr>
                <td>@Html.DisplayFor(modelItem => brand.BrandId)</td>
                <td>@Html.DisplayFor(modelItem => brand.BrandName)</td>
                

                <td>
                    <a asp-controller="Brand" asp-action="Details"
                       asp-route-id="@brand.BrandId"><button type="button" class="btn btn-dark">Details</button></a>|
                    <a asp-controller="Brand" asp-action="Edit"
                       asp-route-id="@brand.BrandId"><button type="button" class="btn btn-info">Edit</button></a>|
                    <a asp-controller="Brand" asp-action="Delete"
                       asp-route-id="@brand.BrandId"><button type="button" class="btn btn-danger">Delete</button></a>|

                </td>

            </tr>
        }
    </tbody>
</table>