CoreShoppingProject/CoreShoppingAdminPortal/Models/Vendor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreShoppingAdminPortal.Models
{
    public class Vendor
    {
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string EmailId { get; set; }

        public double PhoneNo { get; set; }
        public string VendorDescription { get; set; }

        public List<Product> Products { get; set; }
    }
}

CoreShoppingProject/CoreShoppingAdminPortal/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreShoppingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreShoppingAdminPortal.Controllers
{
    public class VendorController : Controller
    {
        ShopDataDbContext context;
        public VendorController(ShopDataDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            var vendors = context.vendors.ToList();

            return View(vendors);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Vendor vendor)
        {
            context.vendors.Add(vendor);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Vendor vend = context.vendors.Where(x => x.VendorId == id).SingleOrDefault();
            ViewBag.authors = new SelectList(context.vendors, "VendorId", "Title");
            return View(vend);
        }
        [HttpPost]
        public ActionResult Edit(Vendor v1)
        {
            Vendor vend = context.vendors.Where(x => x.VendorId == v1.VendorId).SingleOrDefault();

            context.Entry(vend).CurrentValues.SetValues(v1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoreShoppingProject/CoreShoppingAdminPortal/Views/Vendor/Create.cshtml
@model CoreShoppingAdminPortal.Models.Vendor
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Vendor Details</h2>
<form asp-action="create" asp-controller="Vendor">
    <label asp-for="VendorId"></label>
    <input type="text" asp-for="VendorId" />
    <br />
    <label asp-for="VendorName"></label>
    <input type="text" asp-for="VendorName" />
    <br />
    <label asp-for=" EmailId"></label>
    <input type="text" asp-for=" EmailId" />
    <br />
    <label asp-for="PhoneNo"></label>
    <input type="text" asp-for="PhoneNo" />
    <br />
    <label asp-for="VendorDescription"></label>
    <input type="text" asp-for="VendorDescription" />
    <br />

    <input type="submit" value="Create Customer" />
</form>

CoreShoppingProject/CoreShoppingAdminPortal/Views/Vendor/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

CoreShoppingProject/CoreShoppingAdminPortal/Views/Vendor/Index.cshtml
@model IEnumerable<CoreShoppingAdminPortal.Models.Vendor>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<h2>Index</h2>

<table>
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.VendorId)</th>
            <th>@Html.DisplayNameFor(model => model.VendorName)</th>
            <th>@Html.DisplayNameFor(model => model.EmailId)</th>
            <th>@Html.DisplayNameFor(model => model.PhoneNo)</th>
            <th>@Html.DisplayNameFor(model => model.VendorDescription)</th>

            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ordr in Model)
        {

            <tr>
                <td>@Html.DisplayFor(modelItem => ordr.VendorId)</td>
                <td>@Html.DisplayFor(modelItem => ordr.VendorName)</td>
                <td>@Html.DisplayFor(modelItem => ordr.EmailId)</td>
                <td>@Html.DisplayFor(modelItem => ordr.PhoneNo))</td>
                <td>@Html.DisplayFor(modelItem => ordr.VendorDescription)</td>


                <td>

                    <a asp-controller="Order" asp-action="Index"
                       asp-route-id="@ordr.VendorId">Details</a>|
                    <a asp-controller="Order" asp-action="Index"
                       asp-route-id="@ordr.VendorId">Edit</a>|
                    @*<a asp-controller="Order" asp-action="Index"
                        asp-route-id="@ordr.VendorId">Delete</a>*@
                </td>


            </tr>
        }
    </tbody>
</table>