CoreShoppingAdminPortal/Models/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreShoppingAdminPortal.Models
{
    public class ProductCategory
    {
       
            public int ProductCategoryId { get; set; }
            public string CategoryName { get; set; }
            public string CategoryDescription { get; set; }

          public  List<Product> Products { get; set; }
        }
    }

CoreShoppingAdminPortal/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreShoppingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreShoppingAdminPortal.Controllers
{
    public class ProductCategoryController : Controller
    {
        ShopDataDbContext context;
        public ProductCategoryController(ShopDataDbContext _context)
        {
            context = _context;
        }
        public ViewResult Index()
        {
            var pc = context.Categories.ToList();
            return View(pc);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductCategory productcategory)
        {
            context.Categories.Add(productcategory);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ViewResult Details(int id)
        {
            ProductCategory category = context.Categories.
                   Where(x => x.ProductCategoryId == id).SingleOrDefault();
            return View(category);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();
            return View(pc);
        }
        [HttpPost]
        public ActionResult Delete(int id, ProductCategory d1)
        {
            var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();
            context.Categories.Remove(pc);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
              var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();
            //ViewBag.Categories =
            //    new SelectList(context.Categories, "CategoryId", "CategoryName", pc.ProductCategoryId);
            return View(pc);
        }
        [HttpPost]
        public ActionResult Edit(ProductCategory productcategory,int id)
        {
            var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();

            //prod.ProductCategoryId = productcategory.ProductCategoryId;
            //prod.CategoryName = productcategory.CategoryName;
            //prod.CategoryDescription = productcategory.CategoryDescription;
            context.Entry(pc).CurrentValues.SetValues(productcategory);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoreShoppingAdminPortal/Views/ProductCategory/Create.cshtml
@model CoreShoppingAdminPortal.Models.ProductCategory

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>

<h2> Add Productcategory</h2>
&nbsp; &nbsp;
<form asp-action="create" asp-controller="ProductCategory">
    <div class="form-group row">
        <label for="text" class="col-sm-2 col-form-label" asp-for="CategoryName">Category Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" placeholder="Text" asp-for="CategoryName" />
        </div>
            <br />
            <label for="text" class="col-sm-2 col-form-label" asp-for="CategoryDescription">Category Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="Text" asp-for="CategoryDescription" />
            </div>
                <br />
            </div>

            <center>
                <input type="submit" value="Submit" class="btn btn-success" />&nbsp;
                <button class="btn btn-success" asp-controller="ProductCategory" asp-action="Index">

                    Back
                </button>
            </center>
</form>

CoreShoppingAdminPortal/Views/ProductCategory/Delete.cshtml
@model CoreShoppingAdminPortal.Models.ProductCategory

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Are you sure you want to delete ? </h3>
&nbsp; &nbsp; &nbsp;
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(Model => Model.ProductCategoryId)
            </th>

            <th scope="col"> @Html.DisplayNameFor(Model => Model.CategoryName)</th>

            <th scope="col">  @Html.DisplayNameFor(Model => Model.CategoryDescription)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(Model => Model.ProductCategoryId)
            </td>

            <td>
                @Html.DisplayFor(Model => Model.CategoryName)
            </td>

            <td>
                @Html.DisplayFor(Model => Model.CategoryDescription)
            </td>
        </tr>
    </tbody>


</table>
@using (Html.BeginForm("Delete", "ProductCategory", FormMethod.Post))
{
    <center>
        <input type="submit" value="Delete" class="btn btn-success" />&nbsp;
        <button class="btn btn-success" asp-controller="ProductCategory" asp-action="Index">

            Back
        </button>
    </center>
}

CoreShoppingAdminPortal/Views/ProductCategory/Details.cshtml
@model CoreShoppingAdminPortal.Models.ProductCategory
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>ProductCategory Details</h2>
&nbsp;&nbsp;
<table class="table">
    <thead class="thead-dark">
        <tr>

            <th scope="col">
                @Html.DisplayNameFor(Model => Model.ProductCategoryId)
            </th>



            <th scope="col">
                @Html.DisplayNameFor(Model => Model.CategoryName)
            </th>

            <th scope="col">
                @Html.DisplayNameFor(Model => Model.CategoryDescription)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(Model => Model.CategoryDescription)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.CategoryDescription)
            </td>
        </tr>
    </tbody>
</table>
<center>   @Html.ActionLink("Back to List", "Index")</center>

CoreShoppingAdminPortal/Views/ProductCategory/Edit.cshtml
@model CoreShoppingAdminPortal.Models.ProductCategory

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



    <h2>Edit</h2>

    <form asp-action="Edit" asp-controller="ProductCategory">
        <div class="form-group row">
            <input type="hidden" asp-for="ProductCategoryId" />
            <br />

            <label for="text" class="col-sm-2 col-form-label" asp-for="CategoryName">Category Name</label>
            <div class="col-sm-10">
                <input asp-for="CategoryName" />
            </div>
            <br />

            <label for="text" class="col-sm-2 col-form-label" asp-for="CategoryDescription">Category Description</label>
            <div class="col-sm-10">
                <input asp-for="CategoryDescription" />
            </div>
            <br />


        </div>
        <center>
            <input type="submit" value="Edit" class="btn btn-success" />&nbsp;
            <button class="btn btn-success" asp-controller="ProductCategory" asp-action="Index">

                Back
            </button>
        </center>
    </form>

CoreShoppingAdminPortal/Views/ProductCategory/Index.cshtml
@model IEnumerable<CoreShoppingAdminPortal.Models.ProductCategory>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .btn1 {
        margin-right: 3500px;
        margin-top: -10px;
    }
</style>

<center><h2>Product Category Index</h2></center>
    &nbsp;&nbsp;
    <a asp-controller="ProductCategory" asp-action="Create"><button type="button" class="btn btn-info btn1">Create</button></a>
    &nbsp;&nbsp;
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.ProductCategoryId)</th>
                <th>@Html.DisplayNameFor(model => model.CategoryName)</th>
                <th>@Html.DisplayNameFor(model => model.CategoryDescription)</th>

                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model)
            {

                <tr>
                    <td>@Html.DisplayFor(modelItem => category.ProductCategoryId)</td>
                    <td>@Html.DisplayFor(modelItem => category.CategoryName)</td>
                    <td>@Html.DisplayFor(modelItem => category.CategoryDescription)</td>


                    <td>

                        <a asp-controller="ProductCategory" asp-action="Details"
                           asp-route-id="@category.ProductCategoryId"><button type="button" class="btn btn-dark">Details</button></a>|
                        <a asp-controller="ProductCategory" asp-action="Edit"
                           asp-route-id="@category.ProductCategoryId"><button type="button" class="btn btn-info">Edit</button></a>|
                        <a asp-controller="ProductCategory" asp-action="Delete"
                           asp-route-id="@category.ProductCategoryId"><button type="button" class="btn btn-danger">Delete</button></a>|

                    </td>


                </tr>
            }
        </tbody>
    </table>